export const GET_TRANSACTIONS_PENDING = 'GET_TRANSACTIONS_PENDING';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';
